apiVersion: v1
kind: Service
metadata:
  name: notes-api-svc
  labels: 
    group: api-config
spec:
  type: ClusterIP
  selector:             # indicates into which pods ClusterIP provides access
    app: notes-api
  ports:
    - port: 5000    # port exposed outside ClusterIP
      targetPort: 5000    # port exposed by Pod