version: '2'
services:
        api:
            build: .
            links:
                - db
            ports:
                - "5000:5000"
            restart: always
            depends_on:
                db:
                   condition: service_healthy     
            networks:
                - backnet  
        db:
           image: mysql:5.7
           ports:
            - "3306:3306"
           environment:
            MYSQL_ROOT_PASSWORD: notepass
           volumes:
            - ./DB:/docker-entrypoint-initdb.d/:ro
           restart: always
           healthcheck:
                test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password=notepass --silent']
                interval: 3s
                retries: 5
                start_period: 30s
           networks:
                - backnet
networks:
        backnet: