apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notes-api
  template:
    metadata:
      labels:
        app: notes-api
    spec:
      containers:
      - name: notes-api
        image: sank64cr.azurecr.io/sank64cr
        ports:
        - containerPort: 5000
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: DB_HOST
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: DB_USER
          - name: DB_DB
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: DB_DB
---
apiVersion: v1
kind: Service
metadata:
  name: notes-api-svc
  labels: 
    group: api-config
spec:
  type: ClusterIP
  selector:             # indicates into which pods ClusterIP provides access
    app: notes-api
  ports:
    - port: 5000    # port exposed outside ClusterIP
      targetPort: 5000    # port exposed by Pod