apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      volumes:
      - name: mysqlpvc
        persistentVolumeClaim:
          claimName: azure-disk-pvc
      - name: init
        configMap:
          name: mysql-config
      containers:
      - name: db
        image: mysql:5.6
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: MYSQL_ROOT_PASSWORD
        ports:
          - containerPort: 3306
        volumeMounts:
          - name: mysqlpvc
            mountPath: /var/lib/mysql
          - name: init
            mountPath: /docker-entrypoint-initdb.d
            readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels: 
    group: db-config
spec:
  type: ClusterIP
  selector:             # indicates into which pods ClusterIP provides access
    app: db
  ports:
    - port: 3306    # port exposed outside ClusterIP
      targetPort: 3306    # port exposed by Pod
