apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi # bound to the managed-csi persistent volume in Azure
  resources:
    requests:
      storage: 2Gi