apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notes-api
  template:
    metadata:
      labels:
        app: notes-api
    spec:
      containers:
      - name: notes-api
        image: alinadir/note-it-down:k8s
        ports:
        - containerPort: 5000
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: DB_HOST
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: DB_USER
          - name: DB_DB
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: DB_DB